function c = Ahat3B(in1,in2)
%Ahat3B
%    C = Ahat3B(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    17-Feb-2023 15:33:07

r1 = in1(1,:);
r2 = in1(2,:);
r3 = in1(3,:);
t1 = in2(1,:);
t2 = in2(2,:);
t3 = in2(3,:);
c = [r2.*t3-r3.*t2;-r1.*t3+r3.*t1;r1.*t2-r2.*t1];
