function ad_ov = SE3add(in1,in2)
%SE3add
%    AD_OV = SE3add(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2024-01-16 21:47:15

v1_1 = in1(1,:);
v1_2 = in1(2,:);
v1_3 = in1(3,:);
v1_4 = in1(4,:);
v1_5 = in1(5,:);
v1_6 = in1(6,:);
v2_1 = in2(1,:);
v2_2 = in2(2,:);
v2_3 = in2(3,:);
v2_4 = in2(4,:);
v2_5 = in2(5,:);
v2_6 = in2(6,:);
ad_ov = [v1_2.*v2_3-v1_3.*v2_2;-v1_1.*v2_3+v1_3.*v2_1;v1_1.*v2_2-v1_2.*v2_1;v1_2.*v2_6-v1_3.*v2_5+v1_5.*v2_3-v1_6.*v2_2;-v1_1.*v2_6+v1_3.*v2_4-v1_4.*v2_3+v1_6.*v2_1;v1_1.*v2_5-v1_2.*v2_4+v1_4.*v2_2-v1_5.*v2_1];
end
