function ads_ov = SE3adds(in1,in2)
%SE3adds
%    ADS_OV = SE3adds(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2024-01-16 21:47:15

f1 = in2(1,:);
f2 = in2(2,:);
f3 = in2(3,:);
f4 = in2(4,:);
f5 = in2(5,:);
f6 = in2(6,:);
v1_1 = in1(1,:);
v1_2 = in1(2,:);
v1_3 = in1(3,:);
v1_4 = in1(4,:);
v1_5 = in1(5,:);
v1_6 = in1(6,:);
ads_ov = [f2.*v1_3-f3.*v1_2+f5.*v1_6-f6.*v1_5;-f1.*v1_3+f3.*v1_1-f4.*v1_6+f6.*v1_4;f1.*v1_2-f2.*v1_1+f4.*v1_5-f5.*v1_4;f5.*v1_3-f6.*v1_2;-f4.*v1_3+f6.*v1_1;f4.*v1_2-f5.*v1_1];
end
