function Ia_c = SE3Ic2Ia(in1)
%SE3Ic2Ia
%    Ia_c = SE3Ic2Ia(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2024-01-16 21:51:18

I0_1 = in1(1,:);
I0_2 = in1(2,:);
I0_3 = in1(3,:);
I0_4 = in1(4,:);
I0_5 = in1(5,:);
I0_6 = in1(6,:);
I0_7 = in1(7,:);
I0_8 = in1(8,:);
I0_9 = in1(9,:);
I0_10 = in1(10,:);
Ia_c = [I0_1;I0_2;I0_3;I0_7;I0_7;I0_7;I0_4;I0_5;I0_6;0.0;0.0;0.0;0.0;I0_10;-I0_9;-I0_10;0.0;I0_8;I0_9;-I0_8;0.0];
end
