function Icv = SE3Ivd(in1,in2)
%SE3Ivd
%    Icv = SE3Ivd(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2024-01-16 21:47:15

I0_1 = in1(1,:);
I0_2 = in1(2,:);
I0_3 = in1(3,:);
I0_4 = in1(4,:);
I0_5 = in1(5,:);
I0_6 = in1(6,:);
I0_7 = in1(7,:);
I0_8 = in1(8,:);
I0_9 = in1(9,:);
I0_10 = in1(10,:);
v1_1 = in2(1,:);
v1_2 = in2(2,:);
v1_3 = in2(3,:);
v1_4 = in2(4,:);
v1_5 = in2(5,:);
v1_6 = in2(6,:);
Icv = [I0_1.*v1_1+I0_4.*v1_2+I0_5.*v1_3+I0_9.*v1_6-I0_10.*v1_5;I0_2.*v1_2+I0_4.*v1_1+I0_6.*v1_3-I0_8.*v1_6+I0_10.*v1_4;I0_3.*v1_3+I0_5.*v1_1+I0_6.*v1_2+I0_8.*v1_5-I0_9.*v1_4;I0_7.*v1_4-I0_9.*v1_3+I0_10.*v1_2;I0_8.*v1_3-I0_10.*v1_1+I0_7.*v1_5;-I0_8.*v1_2+I0_9.*v1_1+I0_7.*v1_6];
end
