function Iacv = SE3Iavd(in1,in2)
%SE3Iavd
%    Iacv = SE3Iavd(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    2024-01-16 21:51:17

SymMtx6Vec1 = in1(1,:);
SymMtx6Vec2 = in1(2,:);
SymMtx6Vec3 = in1(3,:);
SymMtx6Vec4 = in1(4,:);
SymMtx6Vec5 = in1(5,:);
SymMtx6Vec6 = in1(6,:);
SymMtx6Vec7 = in1(7,:);
SymMtx6Vec8 = in1(8,:);
SymMtx6Vec9 = in1(9,:);
SymMtx6Vec10 = in1(10,:);
SymMtx6Vec11 = in1(11,:);
SymMtx6Vec12 = in1(12,:);
SymMtx6Vec13 = in1(13,:);
SymMtx6Vec14 = in1(14,:);
SymMtx6Vec15 = in1(15,:);
SymMtx6Vec16 = in1(16,:);
SymMtx6Vec17 = in1(17,:);
SymMtx6Vec18 = in1(18,:);
SymMtx6Vec19 = in1(19,:);
SymMtx6Vec20 = in1(20,:);
SymMtx6Vec21 = in1(21,:);
v1_1 = in2(1,:);
v1_2 = in2(2,:);
v1_3 = in2(3,:);
v1_4 = in2(4,:);
v1_5 = in2(5,:);
v1_6 = in2(6,:);
Iacv = [SymMtx6Vec1.*v1_1+SymMtx6Vec7.*v1_2+SymMtx6Vec8.*v1_3+SymMtx6Vec13.*v1_4+SymMtx6Vec16.*v1_5+SymMtx6Vec19.*v1_6;SymMtx6Vec2.*v1_2+SymMtx6Vec7.*v1_1+SymMtx6Vec9.*v1_3+SymMtx6Vec14.*v1_4+SymMtx6Vec17.*v1_5+SymMtx6Vec20.*v1_6;SymMtx6Vec3.*v1_3+SymMtx6Vec8.*v1_1+SymMtx6Vec9.*v1_2+SymMtx6Vec15.*v1_4+SymMtx6Vec18.*v1_5+SymMtx6Vec21.*v1_6;SymMtx6Vec4.*v1_4+SymMtx6Vec13.*v1_1+SymMtx6Vec10.*v1_5+SymMtx6Vec14.*v1_2+SymMtx6Vec11.*v1_6+SymMtx6Vec15.*v1_3;SymMtx6Vec5.*v1_5+SymMtx6Vec10.*v1_4+SymMtx6Vec16.*v1_1+SymMtx6Vec12.*v1_6+SymMtx6Vec17.*v1_2+SymMtx6Vec18.*v1_3;SymMtx6Vec6.*v1_6+SymMtx6Vec11.*v1_4+SymMtx6Vec12.*v1_5+SymMtx6Vec19.*v1_1+SymMtx6Vec20.*v1_2+SymMtx6Vec21.*v1_3];
end
