function vp = SE3LogV(in1,w2c,in3)
%SE3LogV
%    VP = SE3LogV(Omg,w2c,p)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    24-Jun-2022 19:03:00

Omega1 = in1(1,:);
Omega2 = in1(2,:);
Omega3 = in1(3,:);
pn1 = in3(1,:);
pn2 = in3(2,:);
pn3 = in3(3,:);
t2 = Omega1.^2;
t3 = Omega2.^2;
t4 = Omega3.^2;
t5 = Omega1.*Omega2.*w2c;
t6 = Omega1.*Omega3.*w2c;
t7 = Omega2.*Omega3.*w2c;
t11 = Omega1./2.0;
t12 = Omega2./2.0;
t13 = Omega3./2.0;
t8 = t2.*w2c;
t9 = t3.*w2c;
t10 = t4.*w2c;
vp = [pn2.*(t5+t13)-pn1.*(t9+t10-1.0)+pn3.*(t6-t12);-pn2.*(t8+t10-1.0)+pn3.*(t7+t11)+pn1.*(t5-t13);pn1.*(t6+t12)-pn3.*(t8+t9-1.0)+pn2.*(t7-t11)];
