function R = SO3Rodrigues(in1,theta)
%SO3Rodrigues
%    R = SO3Rodrigues(Omega,theta)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    24-Jun-2022 16:31:46

Omg1 = in1(1,:);
Omg2 = in1(2,:);
Omg3 = in1(3,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = Omg1.^2;
t5 = Omg2.^2;
t6 = Omg3.^2;
t7 = Omg1.*t3;
t8 = Omg2.*t3;
t9 = Omg3.*t3;
t10 = t2-1.0;
t11 = Omg1.*Omg2.*t10;
t12 = Omg1.*Omg3.*t10;
t13 = Omg2.*Omg3.*t10;
t14 = t4.*t10;
t15 = t5.*t10;
t16 = t6.*t10;
t17 = -t11;
t18 = -t12;
t19 = -t13;
R = reshape([t15+t16+1.0,t9+t17,-t8+t18,-t9+t17,t14+t16+1.0,t7+t19,t8+t18,-t7+t19,t14+t15+1.0],[3,3]);
